FROM alpine:latest

# Install necessary packages using apk
RUN apk add --no-cache mosquitto

# Expose the port your application listens on
EXPOSE 8883

VOLUME ["/mosquitto/config", "/mosquitto/data", "/mosquitto/log"]

CMD ["/usr/sbin/mosquitto", "-c", "/mosquitto/config/mosquitto.conf"]
